Add pet
azazellokhv/PetFamily pull request #18
Opened 2024-09-18 13:06 UTC by azazellokhv

2024-09-19 08:00 UTC, KirillSachkov requested changes

2024-09-19 08:00 UTC, KirillSachkov commented on backend/src/PetFamily.API/Contracts/AddPetRequest.cs
> +    IFormFileCollection PetPhotos);
Фотографии нужно загружать отдельной фичей, указано в задачии https://s.craft.me/XhPtoLZlK4qbsI

2024-09-19 08:00 UTC, KirillSachkov commented on backend/src/PetFamily.API/Controllers/VolunteersController.cs
> +    private readonly IOptionsSnapshot<MinioOptions> _minioOptions;
Это здесь где-то используется?

2024-09-19 08:00 UTC, KirillSachkov commented on backend/src/PetFamily.Application/Volunteers/AddPet/AddPetHandler.cs
> +        var petId = PetId.NewPetId();
Можно всю эту инициализацию вынести в отдельный приватный метод

2024-09-20 00:38 UTC, azazellokhv commented on backend/src/PetFamily.API/Contracts/AddPetRequest.cs
> +    IFormFileCollection PetPhotos);
Добавление питомца и добавление фотографий разделил на отдельные фичи

2024-09-20 00:38 UTC, azazellokhv commented on backend/src/PetFamily.API/Controllers/VolunteersController.cs
> +    private readonly IOptionsSnapshot<MinioOptions> _minioOptions;
Остатки от вводного занятия по minio - удалил

2024-09-20 00:38 UTC, azazellokhv commented on backend/src/PetFamily.Application/Volunteers/AddPet/AddPetHandler.cs
> +        var petId = PetId.NewPetId();
Вынес в отдельный приватный метод

2024-09-21 04:49 UTC, KirillSachkov approved these changes

2024-09-21 05:34 UTC, merged