Added entity "Pet"
azazellokhv/PetFamily pull request #2
Opened 2024-08-11 06:17 UTC by azazellokhv

2024-08-11 07:29 UTC, SonicMusic requested changes

2024-08-11 07:29 UTC, SonicMusic commented on backend/src/PetFamily.Domain/Models/Pet.cs
> +    public int ContactPhone { get; private set; }
ContactPhone должен быть string

2024-08-11 07:29 UTC, SonicMusic commented on backend/src/PetFamily.Domain/Models/DetailsForAssistance.cs
> +    public int BankCardAssistance { get; private set; }
поменять на string

2024-08-11 12:51 UTC, azazellokhv commented
Свойства с телефонными номерами заменены на string, дополнительно во всех классах реализована "богатая" доменная модель.

2024-08-11 13:48 UTC, KirillSachkov requested changes

2024-08-11 13:48 UTC, KirillSachkov commented on backend/src/PetFamily.Domain/Models/Address.cs
> +    public Guid Id { get; private set; }
У адреса не должно быть Id, это не сущность, а объект значения

2024-08-11 13:48 UTC, KirillSachkov commented on backend/src/PetFamily.Domain/Models/AssistanceStatus.cs
> +    public Guid Id { get; private set; }
Не должно быть Id, это не сущность, а объект значения

2024-08-11 13:48 UTC, KirillSachkov commented on backend/src/PetFamily.Domain/Models/BiologicalSpecies.cs
> +    public string Title { get; private set; }
Лучше Name

2024-08-11 13:48 UTC, KirillSachkov commented on backend/src/PetFamily.Domain/Models/BiologicalSpecies.cs
> +
У вида должен быть список пород

2024-08-11 13:48 UTC, KirillSachkov commented on backend/src/PetFamily.Domain/Models/ColorPet.cs
> +    public Guid Id { get; private set; }
Не должно быть Id, это не сущность, а объект значения

2024-08-11 13:48 UTC, KirillSachkov commented on backend/src/PetFamily.Domain/Models/DetailsForAssistance.cs
> +    public Guid Id { get; private set; }
Не должно быть Id, это не сущность, а объект значения

2024-08-11 13:48 UTC, KirillSachkov commented on backend/src/PetFamily.Domain/Models/DetailsForAssistance.cs
> +        if (contactPhoneAssistance.Length != 11 && IsDigitsOnly(contactPhoneAssistance))
11 вынести в константу

2024-08-11 13:48 UTC, KirillSachkov commented on backend/src/PetFamily.Domain/Models/DetailsForAssistance.cs
> +        foreach (char c in checkString)
Попробуй переделать с помощью LINQ

2024-08-11 13:48 UTC, KirillSachkov commented on backend/src/PetFamily.Domain/Models/Health.cs
> +    public Guid Id { get; private set; }
Не должно быть Id, это не сущность, а объект значения

2024-08-11 13:48 UTC, KirillSachkov commented on backend/src/PetFamily.Domain/Models/Pet.cs
> +        if (string.IsNullOrWhiteSpace(nickname) || nickname.Length > MAX_NICKNAME_LENGTH)
Вынеси в константу

2024-08-11 13:48 UTC, KirillSachkov commented on backend/src/PetFamily.Domain/PetFamily.Domain.csproj
> +      <PackageReference Include="CSharpFunctionalExtensions" Version="2.42.5" />
Достаточно только сюда установить эту библиотеку, во всех остальных проектах её можно будет использовать через этот

2024-08-12 12:09 UTC, azazellokhv commented
Замечания исправил

2024-08-13 06:28 UTC, KirillSachkov approved these changes

2024-08-13 11:46 UTC, merged